# -*- coding: utf-8 -*-
"""Day 1 Assignement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1odRoAAOWBjJxYQEP64uMEOrGwfVetVBC
"""

x=int(input("Enter the value of x:"))
y=int(input("Enter the value of y:"))
z=x**y
print(z)

