# -*- coding: utf-8 -*-
"""Day - 2 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kyqU7VYulReKKcXTm3ZHnrxs29H_f7qv
"""

str = 'book keeper'
bcount = str.count('b')
print("b-",bcount)
ocount = str.count('o')
print("o-",ocount)
kcount = str.count('k')
print("k-",kcount)
ecount = str.count('e')
print("e-",ecount)
pcount = str.count('p')
print("p-",pcount)
rcount = str.count('r')
print("r-",rcount)

