# -*- coding: utf-8 -*-
"""Copy of Day 1 Assignement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alXfFy28rpnqLtp0T0RUGiyIfOM5sqyy
"""

x=int(input("Enter the value of x:"))
y=int(input("Enter the value of y:"))
z=x**y
print(z)

