# -*- coding: utf-8 -*-
"""Day-3 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z69kMPnhV4wesdJWPzxkIk2xzQ35Ks-R
"""

def mod_div(fun):
  def inner(a, b):
    if a < b:
      a, b = b, a
    fun(a, b)   
  return inner
@mod_div
def div(a, b):
  print(a / b)
div(4, 16)