# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HaLWcaIIZurlzflaVxUVTbpkG4E1CoZB
"""

import random
import string

id = ''
characters_list = list(string.ascii_letters + string.digits)
for i in range(6):
  id += random.choice(characters_list)

print(id)